// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PRInfo is the open pull request for the agent's current branch, if any.
 */
export interface PRInfo {
    "url": string;
    "number": number;
    "state": string;
    "title": string;
}

export interface SpawnRequest {
    "Agent": string;
    "Name": string;
    "Repo": string;
    "Prompt": string;
    "Template": string;
    "Network": string;
    "Memory": string;
    "CPUs": string;

    /**
     * USD; engine kills the agent past this budget
     */
    "MaxCost": string;
    "SSH": boolean;
    "ReuseAuth": boolean;
    "Worktree": boolean;
    "DryRun": boolean;
    "NoSeedAuth": boolean;
    "NoGHAuth": boolean;
}
